import type { Metadata } from "next";
import { Domine, Inter, Rubik } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Section from "./components/Section";

const domine = Domine({
  subsets: ["latin"],
  weight: "variable",
  variable: "--font-domine",
});

const rubik = Rubik({
  subsets: ["latin"],
  weight: "variable",
  variable: "--font-rubik",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`relative ${domine.variable} ${rubik.variable}`}>
        <Navbar />
        <Section>{children}</Section>
      </body>
    </html>
  );
}
